export default {
    'I': {
        count: 100,
        props: [
            [ 'properties.weather_idx', 'linear', [0, 99], {overflow: 'clamp'} ],
            [ 'properties.edna_sorted_idx', 'linear', [0, 99], {overflow: 'wrap', offset: 0, repeat: 2} ],
            [ 'properties.edna_sample_idx', 'linear', [0, 1], {overflow: 'wrap', offset: 0} ],
            [ 'properties.filled', 'rnd', [0.8, 1.0] ],
            [ 'properties.colored', 'constant', 0.8 ],
            [ 'properties.round', 'rnd', [0.5, 1.0] ],
            [ 'properties.root_round_chance', 'constant', -1 ],
            [ 'properties.mirror', 'rnd_set', [ 'both' ] ],
            [ 'properties.bee_visible', 'constant', true ],
            [ 'properties.disturbance_pos_r', 'rnd', [0.001, 0.20] ],
            // [ 'properties.disturbance_pos_a', 'rnd', [0, 360] ],
            [ 'element.r', 'rnd', [-180, 180] ],
            [ 'depth.r', 'rnd', [-10, 10] ],
            [ 'depth.tx', 'rnd', [-50, 50] ],
            [ 'depth.ty', 'rnd', [-50, 50] ],
            [ 'animation.bee_anim_type', 'rnd_set', ['ellipse', 'eight', 'loop', 'tri'] ],
            [ 'animation.bee_rotation', 'rnd', [0, 360] ],
            [ 'animation.bee_flip_dir', 'rnd_set', [true, false] ],
            [ 'animation.bee_rx', 'rnd', [200, 650] ],
            [ 'animation.bee_ry', 'rnd', [200, 650] ],
            [ 'animation.bee_noise_amp', 'rnd', [0, 30] ],
            [ 'animation.bee_noise_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.fill_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.form_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.stroked_seed', 'copy', 'properties.weather_idx' ],
        ],
    },
    'II': {
        count: 900,
        props: [
            [ 'properties.weather_idx', 'linear', [100, 999], {overflow: 'clamp'} ],
            [ 'properties.edna_sorted_idx', 'linear', [0, 99], {overflow: 'wrap', offset: 0, repeat: 2} ],
            [ 'properties.edna_sample_idx', 'linear', [0, 1], {overflow: 'wrap', offset: 100} ],
            [ 'properties.filled', 'rnd', [0.4, 0.6] ],
            [ 'properties.colored', 'constant', 0.5 ],
            [ 'properties.round', 'rnd', [0.3, 0.5] ],
            [ 'properties.root_round_chance', 'constant', -1 ],
            [ 'properties.mirror', 'rnd_set', [ 'both' ] ],
            [ 'properties.bee_visible', 'constant', false ],
            [ 'properties.disturbance_pos_r', 'rnd', [0.1, 0.3] ],
            // [ 'properties.disturbance_pos_a', 'rnd', [0, 360] ],
            [ 'element.r', 'rnd', [-180, 180] ],
            [ 'depth.r', 'rnd', [-10, 10] ],
            [ 'depth.tx', 'rnd', [-50, 50] ],
            [ 'depth.ty', 'rnd', [-50, 50] ],
            [ 'animation.bee_anim_type', 'rnd_set', ['ellipse', 'eight', 'loop', 'tri'] ],
            [ 'animation.bee_rotation', 'rnd', [0, 360] ],
            [ 'animation.bee_flip_dir', 'rnd_set', [true, false] ],
            [ 'animation.bee_rx', 'rnd', [200, 650] ],
            [ 'animation.bee_ry', 'rnd', [200, 650] ],
            [ 'animation.bee_noise_amp', 'rnd', [0, 50] ],
            [ 'animation.bee_noise_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.fill_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.form_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.stroked_seed', 'copy', 'properties.weather_idx' ],
        ],
    },
    'III': {
        count: 2200,
        props: [
            [ 'properties.weather_idx', 'linear', [1000, 3199], {overflow: 'clamp'} ],
            [ 'properties.edna_sorted_idx', 'linear', [0, 99], {overflow: 'wrap', offset: 0, repeat: 2} ],
            [ 'properties.edna_sample_idx', 'linear', [0, 1], {overflow: 'wrap', offset: 1000} ],
            [ 'properties.filled', 'rnd', [0.15, 0.20] ],
            [ 'properties.colored', 'constant', 0.5 ],
            [ 'properties.round', 'rnd', [0.20, 0.30] ],
            [ 'properties.root_round_chance', 'constant', -1 ],
            [ 'properties.mirror', 'rnd_set', [ 'x', 'y', 'diag', 'both'] ],
            [ 'properties.bee_visible', 'constant', false ],
            [ 'properties.disturbance_pos_r', 'rnd', [0.2, 0.4] ],
            // [ 'properties.disturbance_pos_a', 'rnd', [0, 360] ],
            [ 'element.r', 'rnd', [-180, 180] ],
            [ 'depth.r', 'rnd', [-10, 10] ],
            [ 'depth.tx', 'rnd', [-50, 50] ],
            [ 'depth.ty', 'rnd', [-50, 50] ],
            [ 'animation.bee_anim_type', 'rnd_set', ['ellipse', 'eight', 'loop', 'tri'] ],
            [ 'animation.bee_rotation', 'rnd', [0, 360] ],
            [ 'animation.bee_flip_dir', 'rnd_set', [true, false] ],
            [ 'animation.bee_rx', 'rnd', [200, 650] ],
            [ 'animation.bee_ry', 'rnd', [200, 650] ],
            [ 'animation.bee_noise_amp', 'rnd', [0, 50] ],
            [ 'animation.bee_noise_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.fill_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.form_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.stroked_seed', 'copy', 'properties.weather_idx' ],
        ],
    },
    'IV': {
        count: 2600,
        props: [
            [ 'properties.weather_idx', 'linear', [3200, 5799], {overflow: 'clamp'} ],
            [ 'properties.edna_sorted_idx', 'linear', [0, 99], {overflow: 'wrap', offset: 0, repeat: 2} ],
            [ 'properties.edna_sample_idx', 'linear', [0, 1], {overflow: 'wrap', offset: 3200} ],
            [ 'properties.filled', 'constant', 0.10 ],
            [ 'properties.colored', 'constant', 0.30 ],
            [ 'properties.round', 'constant', 0.20 ],
            [ 'properties.root_round_chance', 'constant', 0.40 ],
            [ 'properties.mirror', 'rnd_set', [ 'x', 'y', 'diag', 'both'] ],
            [ 'properties.disturbance_pos_r', 'rnd', [0.3, 0.4] ],
            [ 'properties.bee_visible', 'constant', false ],
            // [ 'properties.disturbance_pos_a', 'rnd', [0, 360] ],
            [ 'element.r', 'rnd', [-180, 180] ],
            [ 'depth.r', 'rnd', [-10, 10] ],
            [ 'depth.tx', 'rnd', [-50, 50] ],
            [ 'depth.ty', 'rnd', [-50, 50] ],
            [ 'animation.bee_anim_type', 'rnd_set', ['ellipse', 'eight', 'loop', 'tri'] ],
            [ 'animation.bee_rotation', 'rnd', [0, 360] ],
            [ 'animation.bee_flip_dir', 'rnd_set', [true, false] ],
            [ 'animation.bee_rx', 'rnd', [200, 650] ],
            [ 'animation.bee_ry', 'rnd', [200, 650] ],
            [ 'animation.bee_noise_amp', 'rnd', [0, 50] ],
            [ 'animation.bee_noise_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.fill_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.form_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.stroked_seed', 'copy', 'properties.weather_idx' ],
        ],
    },
    'V': {
        count: 2960,
        props: [
            [ 'properties.weather_idx', 'linear', [5800, 8759], {overflow: 'clamp'} ],
            [ 'properties.edna_sorted_idx', 'linear', [0, 99], {overflow: 'wrap', offset: 0, repeat: 2} ],
            [ 'properties.edna_sample_idx', 'linear', [0, 1], {overflow: 'wrap', offset: 5800} ],
            [ 'properties.filled', 'constant', 0 ],
            [ 'properties.colored', 'constant', 0 ],
            [ 'properties.round', 'rnd', [0.0, 0.10] ],
            [ 'properties.root_round_chance', 'constant', 0.20 ],
            [ 'properties.mirror', 'rnd_set', [ 'x', 'y', 'diag', 'both'] ],
            [ 'properties.bee_visible', 'constant', false ],
            [ 'properties.disturbance_pos_r', 'rnd', [0.3, 0.4] ],
            // [ 'properties.disturbance_pos_a', 'rnd', [0, 360] ],
            [ 'element.r', 'rnd', [-180, 180] ],
            [ 'depth.r', 'rnd', [-10, 10] ],
            [ 'depth.tx', 'rnd', [-50, 50] ],
            [ 'depth.ty', 'rnd', [-50, 50] ],
            [ 'animation.bee_anim_type', 'rnd_set', ['ellipse', 'eight', 'loop', 'tri'] ],
            [ 'animation.bee_rotation', 'rnd', [0, 360] ],
            [ 'animation.bee_flip_dir', 'rnd_set', [true, false] ],
            [ 'animation.bee_rx', 'rnd', [200, 650] ],
            [ 'animation.bee_ry', 'rnd', [200, 650] ],
            [ 'animation.bee_noise_amp', 'rnd', [0, 50] ],
            [ 'animation.bee_noise_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.fill_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.form_seed', 'copy', 'properties.weather_idx' ],
            [ 'general.stroked_seed', 'copy', 'properties.weather_idx' ],
        ],
    },
};
